// svg-scan.mjs — the only "XML" facility the gate gets, and deliberately a small one.
//
// Zero-dependency by design, not by thrift: the gate is what ASSERTS this repo has no dependencies
// (check-buildable-slice guards the absence of a root package.json), so an assertor that itself needed
// `npm install` would undermine the claim it exists to defend.
//
// Group structure reuses topLevelGroups() from the product's own layer-ingest — pure ESM, node-tested,
// and hardened in the 2026-07-26 stage against comments and non-rendered subtrees. The checkers need
// only a few element-level reads on top of that.
import { topLevelGroups } from "../rig-editor/layer-ingest.js";

export function rootTag(svgText) {
  const m = svgText.match(/<svg\b[^>]*>/);
  if (!m) throw new Error("no <svg> root element found");
  return m[0];
}

export function attrOf(tagText, name) {
  const m = tagText.match(new RegExp(`\\b${name}="([^"]*)"`));
  return m ? m[1] : undefined;
}

// Raw tag text of every <tag …> at ANY depth, self-closing or not. Attribute values containing '>'
// would confuse this, exactly as they would the product's own tokenizer — the gate's inputs are
// generated by this repo and never contain one.
export function elements(svgText, tag) {
  return svgText.match(new RegExp(`<${tag}\\b[^>]*?\\/?>`, "g")) || [];
}

export function countElements(svgText, tags) {
  return tags.reduce((n, t) => n + elements(svgText, t).length, 0);
}

export { topLevelGroups };
